eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8767

mybatis:
  type-aliases-package: com.yan.product.entities

spring:
  application:
    name: service-product
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meou?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mariadb
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

#management.metrics.export:
#  influx:
#    enabled: true
#    step: PT30S
#    readTimeout: PT30S
#    batchSize: 20000
#    uri: http://localhost:8086/write
#    userName: root
#    password: root
#    db: metrics
