server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: auth-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meou?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mariadb
    druid:
      initial-size: 4
      max-active: 128
      min-evictable-idle-time-millis: 100000
