server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: true
management:
  security:
    enabled: false
management.metrics.export:
  atlas:
    enabled: true
    step: PT10S
    readTimeout: PT30S
    batchSize: 20000
    uri: http://localhost:7101/api/v1/publish
#management.metrics.export:
#  security:
#    enabled: false
#  influx:
#    enabled: true
#    step: PT30S
#    readTimeout: PT30S
#    batchSize: 20000
#    uri: http://localhost:8086/write
#    userName: admin
#    password: admin
#    db: SpringDB
      