server:
  port: 8081

spring:
  application:
    name: nacos-producer
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8
      username:  cloud_dev
      password:  123456
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          version: 1.0
          group: DEFAULT_GROUP
    sentinel:
      transport:
        port: 8919
        dashboard: localhost:8090
      datasource:
        ds1:
          nacos:
            server-addr: localhost:8848
            dataId: sentinel_flowrule.json
            groupId: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: "*"