server:
  port: 8081
spring:
  application:
    name: nacos-producer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        metadata:
          version: 1.0
          group: DEFAULT_GROUP
    sentinel:
      transport:
        port: 8919
        dashboard: localhost:8090
      datasource:
        ds1:
          file:
            file: "classpath: flowrule.json"
            data-type: json
            rule-type: flow
  sleuth:
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
management:
  endpoints:
    web:
      exposure:
        include: "*"